# Autogenerated code. DO NOT EDIT.
# Generated using basic_to_python.py at 2024-07-23T10:37:16.636893+12:00

from basic import basic
from basic_functions import *

@basic
def basic_example():
    
    _10. FOR.I=1,TO,3
    _20. PRINT("HELLO WORLD")
    print("raw python")
    _30. NEXT.I


if __name__ == '__main__':
    basic_example()
    
